<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login_member extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('member_model');
    }

    public function index()
    {	
    	
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('member/index_member');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('login_member_view');
		}
		else
		{

			$cek_login=$this->member_model->cek_login(
				$this->input->post('username_member'),
				$this->input->post('password_member')
				);

			if( !empty($cek_login))
			{
				
				$this->session->set_userdata('username_member',$cek_login->username_member);
				$this->session->set_userdata('logined', true);
				
				

				redirect('member/index_member');
			}
			else 
			{
				
				print_r($this->session->userdata('username_member'));

			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		redirect("/login_member");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */